google/Xee

README.md
In https://github.com/google/Xee/issues/80 it wasn't obvious to me to pass an Image to an ImageCollection.
This PR adds this as as example.
=> DOC: single open image example

xee/ext.py
Fixed #86.
In the existing code, we're comparing data from Earth Engine, which arrives as floating-point numbers with 7-digit precision, to a masked value that's accurate to 9 digits. This discrepancy prevents a direct match. To address this, I introduced `np.isclose()`, which can match masked value with earth-engine data despite this precision difference.
Let's take an example:
```
import numpy as np
data = [(9999.,), (9999.01,), (9999.1,)]
Previous_Result = np.where( data == 9999, np.nan, data)
Current_Result = np.where( np.isclose(data, 9999), np.nan, data)
print(Previous_Result, Current_Result)
```
Output: 
```
Previous_Result : [[9999.  ] [9999.01] [9999.1 ]] 
Current_Result : [[nan] [nan] [9999.1]]
```
So `np.isclose` is match the value when their difference  is less than `0.1`. …
=> Better handling of setting EE nodata masked value to NaNs values.

README.md, xee/ext.py, xee/ext_integration_test.py
By incorporating the following code into the main branch, i successfully addressed and resolved issue https://github.com/google/Xee/issues/40.(The mentioned internal test case was passed when utilizing the current solution.)
=> Fixed small data discrepancy between Xee and pure computePixels().

xee/ext.py
Fixed: #85.
The current code gives an error(`Pixel grid dimensions (40818x1) must be less than or equal to 32768`) when creating an **lat, lon** **array** for the `image_to_array` conversion, for certain lengthy images. To address this, I've made updates to the code. Now, when generating an lat, lon array for certain lengthy images, I break it down into smaller array based on Users preferred size or default size. This adjustment prevents the above error.
=> Pixel grid dimensions (40818x1) error fixed.

xee/ext.py
I fixed the code of the Lat, Lon data storing mechanism.
The current code store the result based on the `slice of the tiles(small data chunks)` but which gives error on some cases so I update that to `index of tiles(small data chunks)` instead of `slice` to store the data.
=> Lat, Lon storing mechanism updated.

xee/ext.py
Currently, the usage of `np.array()` inside the `_process_coordinate_data`  fails when attempting to merge 1D arrays with different sizes. This can be resolved by replacing np.array() with `np.concatenate()`, which effectively merges 1D arrays with varying shapes into a single 1D array.
Example code:
```
import numpy as np
day1 = np.random.randint(10, size=(5))
print(day1)
day2 = np.random.randint(10, size=(4))
print(day2)
allDays1 = np.array([day1, day2])  # not worked
allDays2 = np.concatenate([day1, day2]) # worked
print(allDays1)
```
=> Fix: Use np.concatenate() instead of np.array() for merging 1D arrays with different sizes

README.md
The README is used to generate [pypi landing page](https://pypi.org/project/xee/) and in this context, your relative links are not pointing anywhere. 
With this very little change, you ensure that the readme page remains valid in other contexts than the GitHub display.
=> fix: use absolut links for pypi

xee/ext.py, xee/ext_integration_test.py
Fixed: #131.
As mentioned in the #131, the current code returns `0 values` for the external boundary of the clipped region. However, this is incorrect, and therefore, these values should be converted to  the `NaN values`.
Approach: Create a global image with a constant value, and then blend this image with the actual image, ensuring that the original image data is preserved in the final image.
=> Convert value outside of ee.Image boundary to NaN.

xee/ext.py, xee/ext_integration_test.py
The existing code of the Xee is incapable of processing the Earth Engine images which have data of  integer datatype. As illustrated in the example below, instead of yielding a "NaN" value, it produces a value that is **one less than** the `ee_mask_value`. For instance, if the `ee_mask_value` is set to -99990, the code will return -99989.
Ex.:
**Before** :
```
image = ee.Image('USGS/GMTED2010').select('be75')
proj_4326 = ee.Projection('EPSG:4326', [1, 0, 0, 0, -1, 0]).atScale(10000)
image = image.reproject(proj_4326)
geom = ee.Geometry.Rectangle( [[-179.99, -80], [179.99, 80]], None, geodesic=False,)
```
```
ic = ee.ImageCollection([image])
ds = xarray.open_dataset(ic, projection=image.projection(), geometry=geom,
ee_mask_value=-99999, engine='ee'
)
ds.be75.values
```
Result:
``` …
```
=> Support added for the int datatype earth engine image.

.github/workflows/lint.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

xee/ext.py, xee/ext_integration_test.py
Xee always used the default value of the `max_retries`, `initial_delay` while calling the `ee.data.computePixels()` through the [robust_getitem](https://github.com/google/Xee/blob/main/xee/ext.py#L484) which affects the QPS(queries per second). To provide Xee users with more control over the QPS, these two variables are now configurable within Xee and can be set by users as well.
=> Feature Update: Retry logic for the ee.data.computePixels update.

README.md, xee/ext.py, xee/ext_integration_test.py
This pr adds support for matching an existing xarray dataset that adheres to rioxarray standards and to support float64 precision with coordinates. 
- It will generally make it easier to merge datasets that come from somewhere else!
- e.g. I have a ton of LiDAR transects as their own tifs. Now I can open them in rioxarray and pass them to load data with the correct transform once instead of resampling again to match.
- more precise transforms if matching closely is important to people
- allows a hacky and not exactly perfect approach to match to an existing xarray's transform if their dims are in float64
- when using double precision geometry objects to match the geometry of an existing dataset, `.getInfo()` seems to change the values so slightly! This motivated …
=> feat: support bbox in in geometry

xee/ext.py, xee/ext_integration_test.py
In the current implementation, we are utilizing [`geometry.bounds().getInfo()`](https://github.com/google/Xee/blob/main/xee/ext.py#L282-L284) to retrieve the bound points. However, this approach yields inconsistent results when the `latitude value` of a point exceeds `104`, resulting in the return of a `constant latitude value`. So I am adding the projection into the bound points to fix this issue.
Example:
```
ee_image = ee.Image("projects/anthromet-prod/assets/1km_uk_nimrod_composite_rainfall_radar/202202120220_nimrod_ng_radar_rainrate_composite_1km_UK")
scale = 5000
projection = ee.Projection("EPSG:4326", [1, 0, 0, 0, -1, 0]).atScale(scale)
ee_image = ee_image.reproject(projection)
point = ee.Geometry.Point(-110.2414893624401 ,104)
distance = 311.5
geometry = point.buffer(distance, …
```
=> Geometry bounds are updated with the projection.

xee/ext.py, xee/ext_integration_test.py
As indicated in the title, Xee **does not** work properly when the **positive scale** is passed. To address this, I have included a logic that can also operate on the positive scale.
The reference notebook, which includes all possible test cases, can be found here [Reference notebook](https://colab.research.google.com/drive/1pNQ5qCqT_SlQHFYIioRTI5By-8yGerZW?resourcekey=0-T6oVflx5Yw9xrfYWNQsD6A&usp=sharing)
=> Support for the positive scale in xee added.

xee/ext.py
The present code retrieves the unit of the CRS using the `crs[0].axis_info` method. However, a `previous version (2.4.2)` of `pyproj` does not provide the unit of the CRS when calling `crs[0].axis_info`. In the context of working Xee in an older version of the pyproj, we must modify this retrieval method.
Reference Code:
```
import ee
ee.Initialize()
import pyproj
from pyproj.crs import CRS
proj = pyproj.Proj(proj='eqc')
crs = pyproj.CRS.from_string(proj.definition_string())
wkt = crs.to_wkt('WKT1_GDAL')
projection = ee.Projection(wkt, [1, 0, 0, 0, -1, 0]).atScale(10000).getInfo()
wkt_str = projection.get('wkt')
crs = CRS(wkt_str)
print(crs.axis_info)
```
Running the aforementioned code with the older version of PyProj results in an empty list.
=> Updating a way to find the Unit Property of the Coordinate Reference System (CRS).

.gitignore
I simply used the python global gitignore and removed everything related to the wheel builder that are not related to this project (namely poetry, hatch, pdm) and things related to pycharm. 
I added back the MacOs `.DS_Store` at the bottom. 
I did this because in another PR I added stuff related to nox and all folder went in the last commit. I think it cost nothing to have a wider gitignore and make sure that new tools can be brought to the package without ignore issues.
=> use the python default gitignore

pyproject.toml
follow-up from #162. Let's see if this is sufficent for a conda release.
=> build: add a fallback version

.github/workflows/ci-build.yml
We have CI testing triggered on PRs. However, we don't want to expose auth-related secrets to run tests on forks, so auth fails by default on PRs coming from external contributors (see [here](https://github.com/google/Xee/actions/runs/10908377089/job/30416416034?pr=175)). We should detect if PR is from a fork and not run CI tests, if true. This PR adds this logic based on https://github.com/orgs/community/discussions/25217.
=> Only run CI tests if PR is not from a fork

xee/ext_integration_test.py
=> Fix integration test warnings re: Dataset.dims

.gitattributes, .gitignore, xee/ext.py, xee/ext_integration_test.py
Fixes #190.
Adds an integration test.
Passes current integration tests:
```
% USE_ADC_CREDENTIALS=1 python -m unittest xee.ext_integration_test                        
.................................
----------------------------------------------------------------------
Ran 33 tests in 378.508s
```
=> Convert ee.Image objects to ee.ImageCollection objects

.github/ISSUE_TEMPLATE/1-bug.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/ISSUE_TEMPLATE/config.yml, README.md
Adds a short Getting Help section to the repo's README file.
=> Add getting help section

README.md, xee/ext_integration_test.py
Instead use ADC credentials if GOOGLE_APPLICATION_CREDENTIALS does not exist. This allows tests to be run without setting an environment variable, which is required by VSCode's Testing (test discovery and management).
=> Don't require USE_ADC_CREDENTIALS=1 to run tests.
